### ISSUE TITLE
Error in multi signature transactions for bitcoin cash

### ISSUE THREAD

**Issue by kunwarshivam** [primal100/pybitcointools#12] opened 2018-02-28 11:51 UTC
Hello @primal100 ,
I am using multi signature transactions for bitcoin cash. I got this error

```
Traceback (most recent call last):
 File "bcc.py", line 1223 , in <module>
   s1 = coin.multisign(tx, i, script, "d2a900b169fe7f576d9c4237f341ca8b21ea16c0a7ef27e1e93bc4351b8f40b3")
 File "/kunwar/anaconda3/lib/python3.6/site-packages/cryptos/coins/base.py", line 223, in multisign
   return multisign(tx, i, script, pk, self.hashcode)
 File "/kunwar/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 433, in multisign
   modtx = signature_form(tx, i, script, hashcode)
 File "/kunwar/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 222, in signature_form
   return uahf_digest(newtx, i)
 File "/kunwar/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 197, in uahf_digest
   o.append(encode_8_bytes(inp['amount']))
KeyError: 'amount'
```
I am using the same code which you gave as an example for multi-signatures. Please address this. Thanks in advance

**Comment by primal100** [comment] 2018-03-03 07:27
Signatures work differently for Bitcoin Cash and has not been implemented for multisig yet.

**Comment by primal100** [comment] 2018-03-03 07:28
Closing as duplicate of #11

**Closed by primal100** 2018-03-03 07:28 UTC
